version: '3.9'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: main
    volumes:
      - vendor:/var/app/vendor
      - ./:/var/app:cached

volumes:
  vendor: